-- Level 2 자동차 종류 별 특정 옵션이 포함된 자동차 수 구하기
SELECT CAR_TYPE, COUNT(CAR_TYPE) AS CARS
  FROM CAR_RENTAL_COMPANY_CAR
 WHERE OPTIONS REGEXP '통풍시트|열선시트|가죽시트'
 GROUP BY CAR_TYPE
 ORDER BY CAR_TYPE ASC;

-- Level 2 성분으로 구분한 아이스크림 총 주문량 (4분 소요)
-- 상반기 동안 각 아이스크림 성분 타입과 성분 타입에 대한 아이스크림의 총주문량
-- 총주문량이 작은 순서대로 조회
SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
  FROM FIRST_HALF A
  JOIN ICECREAM_INFO B
    ON A.FLAVOR = B.FLAVOR
 GROUP BY INGREDIENT_TYPE
 ORDER BY TOTAL_ORDER ASC;

-- Level 3 즐겨찾기가 가장 많은 식당 정보 출력하기 (못풀었음)
-- 음식종류별로 즐겨찾기수가 가장 많은 식당의 음식 종류, ID, 식당 이름, 즐겨찾기수를 조회
-- 음식 종류를 기준으로 내림차순 정렬

-- 즐겨찾기 수 가장 많은 식당 랜덤으로 나오는 결과 (문법상 틀림)
/*
SELECT FOOD_TYPE,REST_ID,REST_NAME,FAVORITES,MAX(FAVORITES) AS FAVORITES
FROM REST_INFO
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC;
*/

-- 식당의 가장 많은 즐겨찾기 수가 동점인 경우 동점인 식당들 나오게됨.
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
  FROM REST_INFO
 WHERE (FOOD_TYPE, FAVORITES) IN (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
      FROM REST_INFO
     GROUP BY FOOD_TYPE
 )
 GROUP BY FOOD_TYPE
 ORDER BY FOOD_TYPE DESC;


-- 식당의 가장 많은 즐겨찾기 수가 동점인 경우 동점인 식당들 나오게됨.
SELECT A.FOOD_TYPE, A.REST_ID, A.REST_NAME, A.FAVORITES
  FROM (SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAVORITES
        FROM REST_INFO
       GROUP BY FOOD_TYPE) AS B
  JOIN REST_INFO AS A
    ON A.FOOD_TYPE= B.FOOD_TYPE
 WHERE A.FAVORITES= B.MAX_FAVORITES
 ORDER BY FOOD_TYPE DESC;


-- Level 3 조건에 맞는 사용자와 총 거래금액 조회하기
-- 완료된 중고 거래의 총금액이 70만 원 이상인 사람의 회원 ID, 닉네임, 총거래금액을 조회
-- 총거래금액을 기준으로 오름차순 정렬

-- 서브쿼리 내부조인
SELECT USER_ID, NICKNAME, TOTAL_SALES
  FROM USED_GOODS_USER B
  JOIN (SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
  FROM USED_GOODS_BOARD
 WHERE STATUS = 'DONE'
 GROUP BY WRITER_ID) A
    ON A.WRITER_ID = B.USER_ID
   AND TOTAL_SALES >= 700000
 ORDER BY TOTAL_SALES ASC;

-- 명시적 내부조인
SELECT B.USER_ID, B.NICKNAME, SUM(A.PRICE) AS TOTAL_SALES
  FROM USED_GOODS_BOARD A, USED_GOODS_USER B
 WHERE A.WRITER_ID = B.USER_ID AND A.STATUS = 'DONE'
 GROUP BY A.WRITER_ID
HAVING TOTAL_SALES >= 700000
 ORDER BY TOTAL_SALES ASC;

-- 묵시적 내부조인
SELECT B.USER_ID, B.NICKNAME, SUM(A.PRICE) AS TOTAL_SALES
  FROM USED_GOODS_BOARD A
  JOIN USED_GOODS_USER B
    ON A.WRITER_ID = B.USER_ID AND A.STATUS = 'DONE'
 GROUP BY A.WRITER_ID
HAVING TOTAL_SALES >= 700000
 ORDER BY TOTAL_SALES ASC;
