-- Level 2 자동차 종류 별 특정 옵션이 포함된 자동차 수 구하기
SELECT CAR_TYPE, COUNT(CAR_TYPE) AS CARS
  FROM CAR_RENTAL_COMPANY_CAR
 WHERE OPTIONS REGEXP '통풍시트|열선시트|가죽시트'
 GROUP BY CAR_TYPE
 ORDER BY CAR_TYPE ASC;

-- Level 2 성분으로 구분한 아이스크림 총 주문량 (4분 소요)
-- 상반기 동안 각 아이스크림 성분 타입과 성분 타입에 대한 아이스크림의 총주문량
-- 총주문량이 작은 순서대로 조회
SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
  FROM FIRST_HALF A
  JOIN ICECREAM_INFO B
    ON A.FLAVOR = B.FLAVOR
 GROUP BY INGREDIENT_TYPE
 ORDER BY TOTAL_ORDER ASC;