-- Level 4 그룹별 조건에 맞는 식당 목록 출력하기
-- 가장 많이 작성한 회원의 리뷰들을 조회
-- (실수회고) 가장 많이 작성한 회원들의 리뷰 조회로 착각했다.

SELECT A.MEMBER_NAME, B.REVIEW_TEXT, DATE_FORMAT(B.REVIEW_DATE,"%Y-%m-%d") AS REVIEW_DATE
  FROM MEMBER_PROFILE AS A
  JOIN REST_REVIEW AS B
    ON A.MEMBER_ID = B.MEMBER_ID
 WHERE A.MEMBER_ID = (SELECT MEMBER_ID FROM REST_REVIEW GROUP BY MEMBER_ID ORDER BY COUNT(*) DESC LIMIT 1)
 ORDER BY B.REVIEW_DATE ASC, B.REVIEW_TEXT ASC;