-- level3 대여 기록이 존재하는 자동차 리스트 구하기
SELECT DISTINCT(A.CAR_ID) AS CAR_ID
  FROM CAR_RENTAL_COMPANY_CAR A
  JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
    ON A.CAR_ID = B.CAR_ID
 WHERE A.CAR_TYPE = '세단'
   AND B.START_DATE BETWEEN '2022-10-01' AND '2022-10-31'
 ORDER BY A.CAR_ID DESC;