-- Level 2 가격이 제일 비싼 식품의 정보 출력하기
SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE
  FROM FOOD_PRODUCT
 WHERE PRICE = (SELECT MAX(PRICE) AS PRICE FROM FOOD_PRODUCT);

-- Level 1 가장 비싼 상품 구하기
SELECT MAX(PRICE) AS MAX_PRICE FROM PRODUCT;

-- Level 1 최댓값 구하기
SELECT DATETIME AS '시간'
  FROM ANIMAL_INS
 ORDER BY DATETIME DESC LIMIT 1;

-- Level 2 최솟값 구하기
SELECT DATETIME AS '시간'
  FROM ANIMAL_INS
 ORDER BY DATETIME ASC LIMIT 1;

-- Level 2 동물 수 구하기
SELECT COUNT(*) AS COUNT FROM ANIMAL_INS;

-- Level 2 중복 제거하기
SELECT COUNT(T.NAME) AS COUNT
  FROM (SELECT DISTINCT(NAME) FROM ANIMAL_INS WHERE NAME IS NOT NULL) T;